# Generated by Django 5.2 on 2025-04-23 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_alter_doctor_hospital_remove_hospital_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('availability', models.CharField(max_length=100)),
                ('consultation_fee_inr', models.IntegerField()),
                ('patients_treated', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=4.0)),
                ('conditions_treated', models.JSONField(blank=True, default=list, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospital.hospital')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
    ]
