# Generated by Django 4.1.13 on 2025-03-13 08:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('availability', models.CharField(default='10 AM - 5 PM', max_length=100)),
                ('fee', models.IntegerField(default=500)),
                ('patients_treated', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=4.0)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profiles', to='hospital.hospital_details')),
            ],
        ),
    ]
