# Generated by Django 4.1.13 on 2025-03-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='conditions_treated',
            field=models.JSONField(blank=True, default=list, help_text='List of conditions or diseases the doctor treats', null=True),
        ),
    ]
