# Generated by Django 5.2 on 2025-04-23 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Doctor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="hospital",
            new_name="hospital_name",
        ),
    ]
