"""
Django settings for healthcare_app_backend project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

<<<<<<< HEAD
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

=======


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


>>>>>>> dfa72382cbf12758b34e97a989f26c0ca80c5543
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-qq7+m2d$p_bdtse0*!=nik^+vd$8&wes(_ud2z29y8_k@_2rwa"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

<<<<<<< HEAD
=======

>>>>>>> dfa72382cbf12758b34e97a989f26c0ca80c5543
# Application definition

INSTALLED_APPS = [
    'user_management',
    'hospital',
    'Doctor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
<<<<<<< HEAD
=======
    'djongo',
>>>>>>> dfa72382cbf12758b34e97a989f26c0ca80c5543
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "healthcare_app_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "healthcare_app_backend.wsgi.application"

<<<<<<< HEAD
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Healthcare',
        'USER': 'postgres',
        'PASSWORD': 'yash1009',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

=======

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'Healthcare',
        'CLIENT': {
            'host': 'localhost',
            'port': 27017,
        }
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
        
#         'NAME': 'Healthcare',
#         'CLIENT': {
#             'host': 'mongodb://localhost:27017/', # Replace with your MongoDB server address
#             'port': 27017,               # Replace with your MongoDB port if different
#             # 'username': 'Krishspatel06', # Replace with your MongoDB username (optional)
#             # 'password': 'IBMhealthcare@0605', # Replace with your MongoDB password (optional)
#             'authSource': 'admin',
#             # 'authMechanism': 'SCRAM-SHA-1',
#         },
#     }
# }

>>>>>>> dfa72382cbf12758b34e97a989f26c0ca80c5543
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

<<<<<<< HEAD
=======

>>>>>>> dfa72382cbf12758b34e97a989f26c0ca80c5543
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

DEBUG = True

<<<<<<< HEAD
=======
DJONGO_USE_NATIVE_JSONFIELD = True
>>>>>>> dfa72382cbf12758b34e97a989f26c0ca80c5543
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOW_ALL_ORIGINS = True

<<<<<<< HEAD
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]
=======

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
]

# AUTH_USER_MODEL = 'user_management.HealthcareUser'
# settings.py

>>>>>>> dfa72382cbf12758b34e97a989f26c0ca80c5543
