# Generated by Django 5.2 on 2025-04-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('available_beds', models.IntegerField()),
                ('diseases_treated', models.JSONField(default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='hospital_ho_name_d8f339_idx')],
            },
        ),
    ]
