# Generated by Django 5.2 on 2025-04-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="user",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="user",
            name="hospital_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="patients_treated",
        ),
        migrations.RemoveField(
            model_name="user",
            name="specialization",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("doctor", "Doctor")],
                default="user",
                max_length=10,
            ),
        ),
    ]
