# Generated by Django 5.2 on 2025-04-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("doctor", "Doctor")],
                default="user",
                max_length=10,
            ),
        ),
    ]
