# Generated by Django 4.1.13 on 2025-02-28 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthcareuser",
            name="confirm_password",
        ),
        migrations.AlterField(
            model_name="healthcareuser",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="healthcareuser",
            name="mobile_number",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_mobile",
                        message="Mobile number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="healthcareuser",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient"), ("doctor", "Doctor")], max_length=10
            ),
        ),
    ]
