# Generated by Django 3.2 on 2025-03-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20250330_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
