# Generated by Django 5.2 on 2025-04-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_add_latitude_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patients_treated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
    ]
