# Generated by Django 3.2 on 2025-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activationtoken',
            name='user_manage_email_2cd815_idx',
        ),
        migrations.AlterField(
            model_name='activationtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
